# Generated by Django 2.1 on 2018-08-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, default='default_dog.png', null=True, upload_to='dog_images/')),
                ('size', models.CharField(choices=[('SM', 'Small (Under 10 lbs)'), ('MD', 'Medium (10 to 40 lbs)'), ('LG', 'Large (40 to 100 lbs)'), ('XL', 'X-Large (Over 100 lbs)')], max_length=2)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
            options={
                'verbose_name': 'Dog',
                'verbose_name_plural': 'Dogs',
                'ordering': ('-pk',),
            },
        ),
    ]
