# Generated by Django 2.1 on 2018-08-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_auto_20180828_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='images',
            field=models.ImageField(blank=True, default='default_dog.png', null=True, upload_to='dog_images/'),
        ),
    ]
