# Generated by Django 2.1 on 2018-08-29 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_auto_20180828_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='images',
            new_name='image',
        ),
    ]
