# Generated by Django 2.1 on 2018-08-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_auto_20180829_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='sex',
            field=models.CharField(default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(choices=[('SM', 'Small (Under 10 lbs)'), ('MD', 'Medium (10 to 40 lbs)'), ('LG', 'Large (40 to 100 lbs)'), ('XL', 'X-Large (Over 100 lbs)')], default='SM', max_length=2),
            preserve_default=False,
        ),
    ]
